postgres:
  image: postgres
  ports:
    - ${POSTGRES_PORT}:5432
  environment:
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  volumes:
    - ./postgres-data:/var/lib/postgresql

mongodb:
  image: mongo
  restart: always
  ports:
    - ${MONGO_PORT}:27017
  environment:
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    MONGO_INITDB_DATABASE: ${MONGO_DB}
    MONGO_DATA_DIR: /data/db
    MONGO_LOG_DIR: /dev/null
  volumes:
    - ./mongo-data:/data/db

mongo-express:
  image: mongo-express
  restart: always
  links:
    - mongodb
  ports:
    - ${MONGO_DASHBOARD_PORT}:8081
  environment:
    ME_CONFIG_MONGODB_SERVER: mongodb
    ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
    ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_DB}
    ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
    ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DASHBOARD_USER}
    ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DASHBOARD_PASSWORD}
    ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
