version: '3.3'

services:
  # Postgres database.
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # Tool for the postgres database.
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgres
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./pgadmin-data:/root/.pgadmin
    restart: unless-stopped
    logging:
      driver: none

  redis:
    container_name: redis
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis-data:/data
    restart: always
