version: '3.3'

services:
  # Postgres database.
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /tmp
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis-data:/data
    restart: always
